/* DRIV-EN DASHBOARD COMMON JS — Shared across all dashboard pages v2 */
(function() {
  'use strict';
  var dashUser = null;
  async function loadComponent(elementId, file) { try { var el = document.getElementById(elementId); if (!el) return; var response = await fetch(file); var html = await response.text(); el.innerHTML = html; } catch (e) { console.error("Failed to load component:", elementId, file, e.message); } }
  window.dashToggleTheme = function() { var current = document.documentElement.getAttribute("data-theme"); var newTheme = current === "dark" ? "light" : "dark"; document.documentElement.setAttribute("data-theme", newTheme); localStorage.setItem("driven-theme", newTheme); updateThemeSwitch(); };
  function updateThemeSwitch() { var current = document.documentElement.getAttribute("data-theme"); var checkbox = document.getElementById("dashThemeCheckbox"); var labelLight = document.getElementById("dashThemeLabelLight"); var labelDark = document.getElementById("dashThemeLabelDark"); if (checkbox) checkbox.checked = (current === "dark"); if (labelLight) labelLight.classList.toggle("active", current === "light"); if (labelDark) labelDark.classList.toggle("active", current === "dark"); }
  window.dashLogout = async function() { try { await fetch("/auth/logout", { method: "POST" }); } catch (e) {} window.location.href = "/public/login.html"; };
  function setPageTitle() { var title = document.body.getAttribute("data-page-title") || "Dashboard"; var titleEl = document.getElementById("dashPageTitle"); if (titleEl) titleEl.textContent = title; }
  async function loadCustomerLogo() { var area = document.getElementById("dashCustomerLogoArea"); if (!area) return; try { var logoRes = await fetch("/auth/get-logo"); var logoData = await logoRes.json(); if (logoData.success && logoData.logo) { localStorage.setItem("driven_customer_logo", logoData.logo); area.innerHTML = '<img src="' + logoData.logo + '" class="dash-customer-logo" alt="Company Logo">'; return; } } catch (e) {} var logoUrl = localStorage.getItem("driven_customer_logo"); if (logoUrl) { area.innerHTML = '<img src="' + logoUrl + '" class="dash-customer-logo" alt="Company Logo">'; } }
  async function loadSession() { try { var response = await fetch("/auth/session"); var data = await response.json(); if (data.authenticated && data.user) { dashUser = data.user; if (data.user.org_id) { localStorage.setItem("driven_customer_id", data.user.org_id); } var greetingEl = document.getElementById("dashGreetingText"); if (greetingEl) { var firstName = data.user.first_name || ""; if (firstName) { greetingEl.innerHTML = "Welcome, <strong>" + firstName + "</strong>"; } else { greetingEl.innerHTML = "Welcome"; } } window.dashUser = data.user; return true; } } catch (e) { console.error("Session load error:", e.message); } return false; }
  async function init() { await loadComponent("dashHeader", "/components/dashboard-header.html"); setPageTitle(); updateThemeSwitch(); await loadCustomerLogo(); await loadSession(); }
  if (document.readyState === "loading") { document.addEventListener("DOMContentLoaded", init); } else { init(); }
  var originalLoadSession = loadSession;
  loadSession = async function() { var result = await originalLoadSession(); document.dispatchEvent(new CustomEvent("dashSessionLoaded", { detail: dashUser })); return result; };
})();
